package dcdtree

import (
	"opencsd/internal/common"
	"opencsd/internal/demux"
	"opencsd/internal/idec"
	"opencsd/internal/interfaces"
	"opencsd/internal/memacc"
	"opencsd/internal/ocsd"
	"slices"
)

// DecodeTree manages the decoding of trace data from a single trace sink.
type DecodeTree struct {
	registry         *DecoderRegister
	treeType         ocsd.DcdTreeSrc
	frameDeformatter *demux.FrameDeformatter
	decodeElements   map[uint8]*DecodeTreeElement

	defaultMapper memacc.Mapper
	createdMapper bool

	iDecoderRoot interfaces.TrcDataIn
	iInstrDecode common.InstrDecode
	iMemAccess   common.TargetMemAccess
	iGenElemOut  interfaces.TrcGenElemIn

	demuxStats ocsd.DemuxStats
}

// NewDecodeTree creates a new Trace Decode Tree using the supplied decoder registry.
// If registry is nil, the package default registry is used.
func NewDecodeTree(srcType ocsd.DcdTreeSrc, formatterCfgFlags uint32, registry *DecoderRegister) *DecodeTree {
	if registry == nil {
		registry = DefaultDecoderRegister()
	}

	dt := &DecodeTree{
		registry:       registry,
		treeType:       srcType,
		decodeElements: make(map[uint8]*DecodeTreeElement),
		iInstrDecode:   idec.NewDecoder(),
	}

	if srcType == ocsd.TrcSrcFrameFormatted {
		dt.frameDeformatter = demux.NewFrameDeformatter()
		dt.frameDeformatter.Configure(formatterCfgFlags)
		dt.iDecoderRoot = dt.frameDeformatter
	}

	return dt
}

// CreateDecodeTree creates a new Trace Decode Tree using the package default registry.
func CreateDecodeTree(srcType ocsd.DcdTreeSrc, formatterCfgFlags uint32) *DecodeTree {
	return NewDecodeTree(srcType, formatterCfgFlags, DefaultDecoderRegister())
}

// Destroy cleans up memory accessors (although GC does mostly).
func (dt *DecodeTree) Destroy() {
	dt.decodeElements = nil
	dt.frameDeformatter = nil
	if dt.createdMapper && dt.defaultMapper != nil {
		dt.defaultMapper = nil
	}
}

// TraceDataIn handles incoming raw byte trace streams into the tree.
func (dt *DecodeTree) TraceDataIn(op ocsd.DatapathOp, index ocsd.TrcIndex, data []byte) (uint32, ocsd.DatapathResp, error) {
	if dt.iDecoderRoot != nil {
		amt, resp, err := dt.iDecoderRoot.TraceDataIn(op, index, data)
		return amt, resp, err
	}

	// Unformatted single trace source fallback
	if dt.treeType == ocsd.TrcSrcSingle {
		elem := dt.decodeElements[0]
		if elem != nil && elem.DataIn != nil {
			amt, resp, err := elem.DataIn.TraceDataIn(op, index, data)
			return amt, resp, err
		}
	}
	return 0, ocsd.RespFatalNotInit, nil
}

// CreateFullDecoder creates a full decoder within the tree for a generic trace config.
func (dt *DecodeTree) CreateFullDecoder(decoderName string, config any) ocsd.Err {
	return dt.createDecoder(decoderName, config, true)
}

// CreatePacketProcessor creates a packet processor within the tree for a generic trace config.
func (dt *DecodeTree) CreatePacketProcessor(decoderName string, config any) ocsd.Err {
	return dt.createDecoder(decoderName, config, false)
}

func (dt *DecodeTree) createDecoder(decoderName string, config any, fullDecoder bool) ocsd.Err {
	registry := dt.registry
	if registry == nil {
		registry = DefaultDecoderRegister()
	}

	mngr, err := registry.GetDecoderMngrByName(decoderName)
	if err != ocsd.OK {
		return err
	}

	type configWithID interface {
		TraceID() uint8
	}
	cfgID, ok := config.(configWithID)
	if !ok {
		return ocsd.ErrInvalidParamType
	}
	csID := cfgID.TraceID()
	routeID := csID
	if dt.treeType == ocsd.TrcSrcSingle {
		routeID = 0
	}
	if routeID >= 0x80 {
		return ocsd.ErrInvalidID
	}

	if _, exists := dt.decodeElements[routeID]; exists {
		return ocsd.ErrAttachTooMany
	}

	var pktIn interfaces.TrcDataIn
	var handle any

	if fullDecoder {
		var err2 ocsd.Err
		pktIn, handle, err2 = mngr.CreateTypedDecoder(int(routeID), config)
		if err2 != ocsd.OK {
			return err2
		}
	} else {
		var err2 ocsd.Err
		pktIn, handle, err2 = mngr.CreateTypedPktProc(int(routeID), config)
		if err2 != ocsd.OK {
			return err2
		}
	}

	if handle == nil {
		return ocsd.ErrFail
	}

	elem := NewDecodeTreeElement(decoderName, mngr, handle, pktIn, true)
	dt.decodeElements[routeID] = elem

	if dt.frameDeformatter != nil && pktIn != nil {
		dt.frameDeformatter.SetIDStream(routeID, pktIn)
	}

	if elem.TraceElemAttach != nil && dt.iGenElemOut != nil {
		elem.TraceElemAttach.ReplaceFirst(dt.iGenElemOut)
	}

	if elem.InstrDecAttach != nil && dt.iInstrDecode != nil {
		elem.InstrDecAttach.ReplaceFirst(dt.iInstrDecode)
	}

	if elem.MemAccAttach != nil && dt.iMemAccess != nil {
		elem.MemAccAttach.ReplaceFirst(dt.iMemAccess)
	}

	return ocsd.OK
}

// RemoveDecoder removes a decoder mapped to the given CSID.
func (dt *DecodeTree) RemoveDecoder(csID uint8) {
	routeID := csID
	if dt.treeType == ocsd.TrcSrcSingle {
		routeID = 0
	}

	if dt.frameDeformatter != nil {
		dt.frameDeformatter.SetIDStream(routeID, nil)
	}
	delete(dt.decodeElements, routeID)
}

// SetGenTraceElemOutI attaches a sink for generic trace element outputs generated by the entire tree.
func (dt *DecodeTree) SetGenTraceElemOutI(outI interfaces.TrcGenElemIn) {
	dt.iGenElemOut = outI
	for _, elem := range dt.decodeElements {
		if elem.TraceElemAttach != nil {
			elem.TraceElemAttach.ReplaceFirst(outI)
		}
	}
}

// SetInstrDecoder attaches the instruction decoder for code-following decoders in the tree.
func (dt *DecodeTree) SetInstrDecoder(instrDec common.InstrDecode) {
	dt.iInstrDecode = instrDec
	for _, elem := range dt.decodeElements {
		if elem.InstrDecAttach != nil {
			elem.InstrDecAttach.ReplaceFirst(instrDec)
		}
	}
}

// SetMemAccessI attaches the memory accessor interface for instruction decoding.
func (dt *DecodeTree) SetMemAccessI(memI common.TargetMemAccess) {
	dt.iMemAccess = memI
	for _, elem := range dt.decodeElements {
		if elem.MemAccAttach != nil {
			elem.MemAccAttach.ReplaceFirst(memI)
		}
	}
}

// GetFrameDeformatter returns the active frame demux.
func (dt *DecodeTree) GetFrameDeformatter() *demux.FrameDeformatter {
	return dt.frameDeformatter
}

// GetFirstElement provides iteration entry point.
func (dt *DecodeTree) GetFirstElement() (uint8, *DecodeTreeElement) {
	ids := dt.sortedElementIDs()
	if len(ids) == 0 {
		return 0, nil
	}
	id := ids[0]
	return id, dt.decodeElements[id]
}

// ForEachElement iterates all registered decode tree elements.
func (dt *DecodeTree) ForEachElement(fn func(csID uint8, elem *DecodeTreeElement)) {
	if fn == nil {
		return
	}
	for _, csID := range dt.sortedElementIDs() {
		elem := dt.decodeElements[csID]
		fn(csID, elem)
	}
}

func (dt *DecodeTree) sortedElementIDs() []uint8 {
	ids := make([]uint8, 0, len(dt.decodeElements))
	for id := range dt.decodeElements {
		ids = append(ids, id)
	}
	slices.Sort(ids)
	return ids
}
